### 회원가입 API
POST {{host_api}}/api/v1/member
Content-Type: application/json

{
    "email": "will.seungho@gmail.com",
    "name": "강승호",
    "profileUrl": "http://profile.com",
    "major": "IT_COMPUTER",
    "classNumber": 201610323
}
> {%
client.global.set("AUTHORIZATION", response.body["data"])
 %}


### 내 정보를 가져오는 API
GET {{host_api}}/api/v1/member
Authorization: Bearer {{AUTHORIZATION}}


### 내 정보를 수정하는 API
PUT {{host_api}}/api/v1/member
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "name": "will",
    "profileUrl": null,
    "major": "IT_ICT",
    "classNumber": 201610333
}


### 특정 회원의 정보를 불러오는 API
GET {{host_api}}/api/v1/member/1
Authorization: Bearer {{AUTHORIZATION}}
