version: "3"
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
  admin:
    build: ./potato-admin
    ports:
      - 9000:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
