server:
  port: 8080
spring:
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
    include:
      - domain
      - rds
      - thirdparty
      - swagger
      - cloud
logging:
  file:
    path: logs/api/
