server:
  port: 8080
spring:
  session:
    store-type: jdbc
  profiles:
    active: local
    include:
      - domain
      - rds
      - thirdparty
      - swagger
      - cloud
  datasource:
    data: classpath:schema/schema-session.sql
