### 조직 생성 API
POST {{host_api}}/api/v1/organization
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "subDomain": "potato",
    "name": "감자팀",
    "description": "테스트2 그룹입니다.",
    "profileUrl": "https://avatars.githubusercontent.com/u/48153675?v=4"
}


### 조직 조회 API
GET {{host_api}}/api/v1/organization/potato



### 조직 리스트 조회 API
GET {{host_api}}/api/v1/organization/list



### 조직 리스트 조회 API
GET {{host_api}}/api/v1/organization/my
Authorization: Bearer {{AUTHORIZATION}}



### 조직에 가입 신청을 하는 API
POST {{host_api}}/api/v1/organization/join/apply/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}



### 그룹 가입 신청을 취소하는 API
PUT {{host_api}}/api/v1/organization/join/cancel/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}



### 조직에서 탈퇴하는 API
DELETE {{host_api}}/api/v1/organization/leave/potato
Authorization: Bearer {{AUTHORIZATION}}
