### 조직 생성 API
POST {{host_api}}/api/v1/organization
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "subDomain": "potato",
    "name": "감자",
    "description": "개발의 감을 잡자",
    "profileUrl": "https://avatars.githubusercontent.com/u/48153675?v=4"
}


### 특정 동아리 상세 조회 API
GET {{host_api}}/api/v1/organization/potato



### 동아리 리스트 조회 API
GET {{host_api}}/api/v1/organization/list?size=5&lastOrganizationId=0



### 내가 속한 동아리 리스트 조회 API
GET {{host_api}}/api/v1/organization/my
Authorization: Bearer {{AUTHORIZATION}}



### 동아리에 가입 신청을 하는 API
POST {{host_api}}/api/v1/organization/join/apply/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}



### 동아리 가입 신청을 취소하는 API
PUT {{host_api}}/api/v1/organization/join/cancel/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}



### 동아리에서 탈퇴하는 API
DELETE {{host_api}}/api/v1/organization/leave/potato
Authorization: Bearer {{AUTHORIZATION}}


### 동아리 팔로우 하기
POST {{host_api}}/api/v1/organization/follow/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}
