version: "3"
services:
  dev:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 8081:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  admin:
    image: ${ADMIN_IMAGE}:${TAG}
    ports:
      - 9001:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  redis:
    image: redis
    command: redis-server --port 6379
    ports:
      - 6379:6379
