version: "3"
services:
  dev:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 8082:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  admin:
    image: ${ADMIN_IMAGE}:${TAG}
    ports:
      - 9002:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
