version: "3"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 8082:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    volumes:
      - ~/logs/api:/logs/api
    links:
      - "db:redis"
  admin:
    image: ${ADMIN_IMAGE}:${TAG}
    ports:
      - 9002:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    volumes:
      - ~/logs/admin:/logs/admin
    links:
      - "db:redis"
  db:
    image: redis
    command: redis-server --port 6379
    hostname: redis
    volumes:
      - ~/db/data:/data
