ALTER TABLE `SPRING_SESSION_ATTRIBUTES`
    DROP INDEX `SPRING_SESSION_ATTRIBUTES_IX1`;

DROP TABLE `SPRING_SESSION_ATTRIBUTES`;

ALTER TABLE `SPRING_SESSION`
    DROP INDEX `SPRING_SESSION_IX1`;

DROP TABLE `SPRING_SESSION`;
