spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.default_batch_fetch_size: 1000
      hibernate.query.in_clause_parameter_padding: true
      hibernate.connection.provider_disables_autocommit: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      auto-commit: false
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:potato;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.hibernate.type: trace
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379
---

spring:
  profiles: beta
  jpa:
    hibernate:
      ddl-auto: none
---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
---
