spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    data: classpath:schema/schema-session.sql
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:potato;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
---
spring:
  profiles: dev, prod
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.default_batch_fetch_size: 1000
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
---

