server:
  port: 9000
spring:
  profiles:
    active: local
    include:
      - domain
      - thirdparty
      - rds
      - cloud
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  file:
    path: logs/admin/
