### 조직의 정보를 변경하는 API
PUT {{host}}/api/v1/organization/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "name": "감자"
}


### 가입 신청을 수락 하는 API
PUT {{host}}/api/v1/organization/join/approve/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "targetMemberId": 2
}

### 가입 신청을 거절 하는 API
PUT {{host}}/api/v1/organization/join/deny/potato
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "targetMemberId": 2
}


### 관리자가 일반 멤버를 강퇴시키는 API
DELETE {{host}}/api/v1/organization/kick/potato?targetMemberId=2
Authorization: Bearer {{AUTHORIZATION}}
